### ISSUE TITLE
error running avail: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by elsehow** [srn/avail#9]
whenever i run `avail` or `avail -h`, i see the following

```shell
usr/local/lib/node_modules/avail/index.js:13
    results = results.map(function (domain) {
                     ^

TypeError: Cannot read property 'map' of undefined
    at Request._callback (/usr/local/lib/node_modules/avail/index.js:13:22)
    at Request.self.callback (/usr/local/lib/node_modules/avail/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/avail/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/avail/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

```shell
☁ npm -v
2.14.4
☁ node -v
v4.1.0
```

**Comment by srn** [comment]
I just did a revamp of the module today. Install it again and it should work.
